public enum State {
    CHOIX_PROFIL,
    CHOIX_CLIENT,
    ACTION,
    CREATION,
    CREATION_CLIENT,
    CREATION_HEBERGEMENT,
    CREATION_CHAMBRE,
    RESERVER,
    RESERVATIONS,
    CHOIX_CHAMBRE,
    RESERVATION_VALIDEE
}
